### PR TITLE
Add naming checks

### LINKED ISSUE #1: camelCase only
Should we add a lint to check that identifiers only use camelCase? It's easy to forget to add those tags.

### PR DESCRIPTION
**Pull request by ahl**
From README.md:

- All type names should be PascalCase.
- All `operation_id`s should be snake_case.
- All operation properties should be snake_case.
- All struct (and struct enum variant) members should be snake_case.

Many changes are required in Omicron because we're about 50/50 between snake and camel for object properties. I think we should go snake rather than camel because the strongest standard I can discern is that folks use whatever's idiomatic in their server implementation language.

Closes #1

### CODE REVIEW

**Comment by david-crespo** [comment]
`snake_case` for properties makes sense. Camel was convenient for us in the TS client, though. Now we will either need runtime conversions between camel and snake or decide we don't care and just use the snake case properties on API objects.

**Comment by ahl** [comment]
@david-crespo please advise here. In progenitor we take the approach of renaming properties/parameters from whatever the spec says to snake_case. It sounds like the TS generator may not do that renaming.

**Comment by david-crespo** [comment]
It does not, but we can either patch it or finally spend the time to add a TS generator to Progenitor.

**Review by david-crespo — APPROVED** [review]
I reserve the right to get slightly freaked out when this is actually applied to Nexus.

**Comment by ahl** [comment]
> I reserve the right to get slightly freaked out when this is actually applied to Nexus.

Noted!

**Pull request merged**
